// src/lib/components/organisms/AnalyseEvolution.svelte
<script lang="ts">
	import Card from '$lib/components/atoms/Card.svelte';
	import EmptyState from '$lib/components/molecules/EmptyState.svelte';
	import type { RepartitionFoodType } from '$lib/domain/repartition.calc';
	import ChartLine from '@lucide/svelte/icons/chart-line';
	import Beef from '@lucide/svelte/icons/beef';
	import Drumstick from '@lucide/svelte/icons/drumstick';
	import Fish from '@lucide/svelte/icons/fish';

	type StatutJour = 'OK' | 'DEFICIT' | 'EXCES' | 'SANS_DONNEE';

	interface JourAnalyse {
		date: string;
		totalKcal: number;
		der: number;
		pctDER: number;
		grammesParType: Record<RepartitionFoodType, number>;
		statut: StatutJour;
	}

	export interface AnalyseOkResponse {
		success: true;
		rer: number;
		der: number;
		jours: JourAnalyse[];
		moyennePctDER: number | null;
		tauxConformitePct: number | null;
		moyenneGrammesParType: Record<RepartitionFoodType, number>;
	}

	let { analyse }: { analyse: AnalyseOkResponse } = $props();

	const ECHELLE_MAX_PCT = 150;

	const barColor: Record<StatutJour, string> = {
		OK: 'bg-success',
		DEFICIT: 'bg-destructive',
		EXCES: 'bg-warning',
		SANS_DONNEE: 'bg-muted'
	};

	function barHeightPct(jour: JourAnalyse): number {
		if (jour.statut === 'SANS_DONNEE') return 4;
		return Math.max(4, Math.min(100, (jour.pctDER / ECHELLE_MAX_PCT) * 100));
	}

	function formatDateCourte(isoDate: string): string {
		return new Date(isoDate).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' });
	}

	function formatDateTooltip(jour: JourAnalyse): string {
		if (jour.statut === 'SANS_DONNEE') return `${formatDateCourte(jour.date)} — aucune donnée`;
		return `${formatDateCourte(jour.date)} — ${Math.round(jour.totalKcal)} / ${Math.round(jour.der)} kcal (${jour.pctDER}%)`;
	}

	const foodTypeIcon: Record<RepartitionFoodType, typeof Beef> = {
		croquette: Drumstick,
		patee: Beef,
		friandise: Fish
	};

	const foodTypeLabel: Record<RepartitionFoodType, string> = {
		croquette: 'Croquette',
		patee: 'Pâtée',
		friandise: 'Friandise'
	};

	const joursAvecDonnee = $derived(analyse.jours.some((j) => j.statut !== 'SANS_DONNEE'));
</script>

{#if !joursAvecDonnee}
	<EmptyState
		icon={ChartLine}
		title="Pas encore de données"
		description="L'analyse se remplira au fil des jours renseignés."
	/>
{:else}
	<Card>
		{#snippet header()}
			<h3 class="text-[17px] leading-tight">Apport calorique quotidien vs besoin (DER)</h3>
		{/snippet}

		<div class="flex h-40 items-end gap-1">
			{#each analyse.jours as jour (jour.date)}
				<div class="group relative flex flex-1 flex-col items-center justify-end" title={formatDateTooltip(jour)}>
					<div
						class="w-full rounded-t transition-transform group-hover:scale-x-110 {barColor[jour.statut]}"
						style={`height: ${barHeightPct(jour)}%`}
					></div>
				</div>
			{/each}
		</div>
		<div class="flex justify-between text-xs text-muted-foreground">
			<span>{formatDateCourte(analyse.jours[0].date)}</span>
			<span>{formatDateCourte(analyse.jours[analyse.jours.length - 1].date)}</span>
		</div>

		<div class="flex flex-wrap gap-3 text-xs text-muted-foreground">
			<span class="flex items-center gap-1"><span class="size-2 rounded-full bg-success"></span> Conforme (±10% du DER)</span>
			<span class="flex items-center gap-1"><span class="size-2 rounded-full bg-destructive"></span> Déficit</span>
			<span class="flex items-center gap-1"><span class="size-2 rounded-full bg-warning"></span> Excès</span>
			<span class="flex items-center gap-1"><span class="size-2 rounded-full bg-muted"></span> Sans donnée</span>
		</div>
	</Card>

	<div class="grid grid-cols-2 gap-4">
		<Card class="items-center text-center">
			<p class="font-heading text-3xl font-extrabold text-primary">
				{analyse.moyennePctDER !== null ? `${analyse.moyennePctDER}%` : '—'}
			</p>
			<p class="text-xs text-muted-foreground">Apport moyen / DER</p>
		</Card>
		<Card class="items-center text-center">
			<p class="font-heading text-3xl font-extrabold text-secondary">
				{analyse.tauxConformitePct !== null ? `${analyse.tauxConformitePct}%` : '—'}
			</p>
			<p class="text-xs text-muted-foreground">Jours conformes</p>
		</Card>
	</div>

	<Card>
		{#snippet header()}
			<h3 class="text-[17px] leading-tight">Répartition moyenne par jour</h3>
		{/snippet}
		<div class="flex flex-col gap-1.5">
			{#each Object.entries(analyse.moyenneGrammesParType) as [type, grammes] (type)}
				{#if grammes > 0}
					{@const Icon = foodTypeIcon[type as RepartitionFoodType]}
					<div class="flex items-center justify-between text-sm">
						<span class="flex items-center gap-2 text-foreground">
							<Icon class="size-4 text-muted-foreground" />
							{foodTypeLabel[type as RepartitionFoodType]}
						</span>
						<span class="font-heading font-semibold text-foreground">{grammes.toFixed(0)} g/j</span>
					</div>
				{/if}
			{/each}
		</div>
		<p class="text-xs text-muted-foreground">
			DER de référence actuel du chat : {Math.round(analyse.der)} kcal/j (RER {Math.round(analyse.rer)} kcal).
		</p>
	</Card>
{/if}

// mobile/src/design-system/organisms/AnalyseEvolution.tsx
import { View } from 'react-native';
import { ChartLine, Beef, Drumstick, Fish } from 'lucide-react-native';
import type { AnalyseOkResponse, JourAnalyse, StatutJourAnalyse } from '@shared/analyse';
import type { RepartitionFoodType } from '@shared/repartition';
import { Card } from '../atoms/Card';
import { Text } from '../atoms/Text';
import { EmptyState } from '../molecules/EmptyState';
import { colors, spacing } from '../tokens';

const ECHELLE_MAX_PCT = 150;

const barColor: Record<StatutJourAnalyse, string> = {
	OK: colors.success,
	DEFICIT: colors.destructive,
	EXCES: colors.warning,
	SANS_DONNEE: colors.muted
};

function barHeightPct(jour: JourAnalyse): number {
	if (jour.statut === 'SANS_DONNEE') return 4;
	return Math.max(4, Math.min(100, (jour.pctDER / ECHELLE_MAX_PCT) * 100));
}

function formatDateCourte(isoDate: string): string {
	return new Date(isoDate).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' });
}

const foodTypeIcon = { croquette: Drumstick, patee: Beef, friandise: Fish } as const;
const foodTypeLabel: Record<RepartitionFoodType, string> = { croquette: 'Croquette', patee: 'Pâtée', friandise: 'Friandise' };

interface AnalyseEvolutionProps {
	analyse: AnalyseOkResponse;
}

export function AnalyseEvolution({ analyse }: AnalyseEvolutionProps) {
	const joursAvecDonnee = analyse.jours.some((j) => j.statut !== 'SANS_DONNEE');

	if (!joursAvecDonnee) {
		return <EmptyState icon={ChartLine} title="Pas encore de données" description="L'analyse se remplira au fil des jours renseignés." />;
	}

	return (
		<View style={{ gap: spacing.lg }}>
			<Card style={{ gap: spacing.sm }}>
				<Text variant="heading">Apport calorique quotidien vs besoin (DER)</Text>

				<View style={{ flexDirection: 'row', alignItems: 'flex-end', gap: 2, height: 140 }}>
					{analyse.jours.map((jour) => (
						<View key={jour.date} style={{ flex: 1, height: '100%', justifyContent: 'flex-end' }}>
							<View style={{ height: `${barHeightPct(jour)}%`, backgroundColor: barColor[jour.statut], borderRadius: 3, minHeight: 4 }} />
						</View>
					))}
				</View>
				<View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
					<Text variant="caption" color="muted">
						{formatDateCourte(analyse.jours[0].date)}
					</Text>
					<Text variant="caption" color="muted">
						{formatDateCourte(analyse.jours[analyse.jours.length - 1].date)}
					</Text>
				</View>

				<View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }}>
					{(
						[
							['Conforme (±10% du DER)', colors.success],
							['Déficit', colors.destructive],
							['Excès', colors.warning],
							['Sans donnée', colors.muted]
						] as const
					).map(([label, color]) => (
						<View key={label} style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
							<View style={{ width: 8, height: 8, borderRadius: 4, backgroundColor: color }} />
							<Text variant="caption" color="muted">
								{label}
							</Text>
						</View>
					))}
				</View>
			</Card>

			<View style={{ flexDirection: 'row', gap: spacing.md }}>
				<Card style={{ flex: 1, alignItems: 'center', gap: 2 }}>
					<Text variant="title" color="primary" style={{ fontSize: 28 }}>
						{analyse.moyennePctDER !== null ? `${analyse.moyennePctDER}%` : '—'}
					</Text>
					<Text variant="caption" color="muted">
						Apport moyen / DER
					</Text>
				</Card>
				<Card style={{ flex: 1, alignItems: 'center', gap: 2 }}>
					<Text variant="title" color="secondary" style={{ fontSize: 28 }}>
						{analyse.tauxConformitePct !== null ? `${analyse.tauxConformitePct}%` : '—'}
					</Text>
					<Text variant="caption" color="muted">
						Jours conformes
					</Text>
				</Card>
			</View>

			<Card style={{ gap: spacing.sm }}>
				<Text variant="heading">Répartition moyenne par jour</Text>
				{(Object.entries(analyse.moyenneGrammesParType) as [RepartitionFoodType, number][])
					.filter(([, grammes]) => grammes > 0)
					.map(([type, grammes]) => {
						const Icon = foodTypeIcon[type];
						return (
							<View key={type} style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
								<View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}>
									<Icon size={16} color={colors.mutedForeground} />
									<Text>{foodTypeLabel[type]}</Text>
								</View>
								<Text variant="bodyMedium">{grammes.toFixed(0)} g/j</Text>
							</View>
						);
					})}
				<Text variant="caption" color="muted">
					DER de référence actuel du chat : {Math.round(analyse.der)} kcal/j (RER {Math.round(analyse.rer)} kcal).
				</Text>
			</Card>
		</View>
	);
}
