// mobile/src/design-system/organisms/DailyMealSchedule.tsx
import { useMemo, useState } from 'react';
import { View, Alert as RNAlert } from 'react-native';
import { Drumstick, Beef, Fish, RotateCcw, SlidersHorizontal, Check } from 'lucide-react-native';
import type { RepartitionOkResponse, RepasRepartition } from '@shared/repartition';
import { Card } from '../atoms/Card';
import { Text } from '../atoms/Text';
import { Badge } from '../atoms/Badge';
import { Checkbox } from '../atoms/Checkbox';
import { Button } from '../atoms/Button';
import { Progress } from '../atoms/Progress';
import { Alert } from '../molecules/Alert';
import { QuantitySlider } from '../molecules/QuantitySlider';
import { RationScoreCard } from './RationScoreCard';
import { RationSummaryCard } from './RationSummaryCard';
import { colors, spacing } from '../tokens';
import { usePatchMealEntry, useResetRepartition } from '../../api/today';

const foodTypeIcon = { croquette: Drumstick, patee: Beef, friandise: Fish } as const;

function formatHeure(consumedAt: string): string {
	return new Date(consumedAt).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
}

function labelDonne(repas: RepasRepartition): string {
	return repas.distributionMode === 'distributeur_automatique' ? 'Donné (auto)' : 'Donné à la main';
}

function formatPaquets(paquets: number): string {
	return `${paquets % 1 === 0 ? paquets : paquets.toFixed(1)} paquet${paquets > 1 ? 's' : ''}`;
}

/** Affichage de la quantité confirmée par le serveur — jamais recalculée (CLAUDE.md règle 9). */
function formatQuantite(repas: RepasRepartition): string {
	if (repas.foodType === 'patee' && repas.paquets !== null) return formatPaquets(repas.paquets);
	if (repas.doses !== null) return `${repas.doses} dose${repas.doses > 1 ? 's' : ''} (${repas.quantiteG} g)`;
	return `${repas.quantiteG} g`;
}

/** Aperçu live pendant le drag du slider, avant tout commit serveur — seule exception à la règle
 * ci-dessus : la valeur n'existe encore nulle part côté serveur, un round-trip par pixel glissé n'est
 * pas envisageable. La quantité persistée reste toujours re-arrondie côté API au relâchement
 * (`mealEntry.service.ts`), ce qui peut différer légèrement de cet aperçu. */
function formatQuantitePreview(repas: RepasRepartition, liveValueG: number): string {
	if (repas.foodType === 'patee' && repas.food.packageSizeG) return formatPaquets(liveValueG / repas.food.packageSizeG);
	if (repas.distributionMode === 'distributeur_automatique' && repas.food.doseDistributeurG) {
		const doses = Math.round(liveValueG / repas.food.doseDistributeurG);
		return `${doses} dose${doses > 1 ? 's' : ''} (${liveValueG} g)`;
	}
	return `${liveValueG} g`;
}

function sliderStep(repas: RepasRepartition): number {
	if (repas.foodType === 'patee' && repas.food.packageSizeG) return repas.food.packageSizeG / 2;
	if (repas.distributionMode === 'distributeur_automatique' && repas.food.doseDistributeurG) {
		return repas.food.doseDistributeurG;
	}
	return 0.5;
}

interface DailyMealScheduleProps {
	repartition: RepartitionOkResponse;
	catId: string;
	date: string;
	onNavigateToHref?: (href: string) => void;
}

export function DailyMealSchedule({ repartition, catId, date, onNavigateToHref }: DailyMealScheduleProps) {
	const patchMealEntry = usePatchMealEntry(catId, date);
	const resetRepartition = useResetRepartition(catId, date);
	const [ajustementOuvertId, setAjustementOuvertId] = useState<string | null>(null);

	const repasDonnes = repartition.repas.filter((r) => r.validated).length;
	const avancementPct = repartition.repas.length > 0 ? Math.round((repasDonnes / repartition.repas.length) * 100) : 0;
	const prochainRepas = repartition.repas.find((r) => !r.validated) ?? null;

	const groupesHoraires = useMemo(() => {
		const parHeure = new Map<string, RepasRepartition[]>();
		for (const repas of repartition.repas) {
			const liste = parHeure.get(repas.consumedAt) ?? [];
			liste.push(repas);
			parHeure.set(repas.consumedAt, liste);
		}
		return [...parHeure.entries()]
			.sort(([a], [b]) => new Date(a).getTime() - new Date(b).getTime())
			.map(([consumedAt, repasList]) => {
				const kcalTotal = repasList.reduce((somme, r) => somme + r.kcal, 0);
				return {
					consumedAt,
					repasList,
					kcalTotal,
					pctDER: repartition.der > 0 ? Math.round((kcalTotal / repartition.der) * 100) : 0
				};
			});
	}, [repartition.repas, repartition.der]);

	function handleToggleValidated(repas: RepasRepartition, validated: boolean) {
		patchMealEntry.mutate({ id: repas.id, input: { validated, ...(validated ? { quantityG: repas.quantiteG } : {}) } });
		if (validated) setAjustementOuvertId(null);
	}

	function handleSliderCommit(repas: RepasRepartition, value: number) {
		patchMealEntry.mutate({ id: repas.id, input: { quantityG: value } });
	}

	function handleReset() {
		RNAlert.alert(
			'Réinitialiser la journée ?',
			"Tous les repas déjà cochés « donné » ou ajustés seront effacés et recalculés depuis la routine.",
			[
				{ text: 'Annuler', style: 'cancel' },
				{ text: 'Réinitialiser', style: 'destructive', onPress: () => resetRepartition.mutate() }
			]
		);
	}

	return (
		<View style={{ gap: spacing.lg }}>
			<RationScoreCard score={repartition.ration.score} onNavigateToHref={onNavigateToHref} />

			{repartition.avertissements.map((avertissement, i) => (
				<Alert key={i} variant="warning" message={avertissement} />
			))}

			<RationSummaryCard repartition={repartition} />

			<Card style={{ gap: spacing.md }}>
				<View style={{ flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm }}>
					<View style={{ flex: 1, gap: 2 }}>
						<Text variant="heading">Repas du jour</Text>
						<Text variant="caption" color="muted">
							{repartition.repas.length === 0
								? 'Aucun créneau prévu aujourd’hui.'
								: repasDonnes === repartition.repas.length
									? 'Tous les repas ont été donnés.'
									: prochainRepas
										? `Prochain : ${formatHeure(prochainRepas.consumedAt)} — ${formatQuantite(prochainRepas)} de ${prochainRepas.food.name}`
										: ''}
						</Text>
					</View>
					<Badge label={`${repasDonnes} / ${repartition.repas.length} donnés`} variant={repasDonnes === repartition.repas.length ? 'success' : 'default'} />
				</View>

				<Progress positionPct={avancementPct} color={repasDonnes === repartition.repas.length ? colors.success : colors.primary} />

				<View>
					{groupesHoraires.map((groupe, i) => {
						const tousValides = groupe.repasList.every((r) => r.validated);
						return (
							<View key={groupe.consumedAt} style={{ flexDirection: 'row', gap: spacing.md }}>
								<View style={{ alignItems: 'center', width: 12 }}>
									<View
										style={{
											marginTop: 6,
											width: 12,
											height: 12,
											borderRadius: 6,
											backgroundColor: tousValides ? colors.success : colors.primary
										}}
									/>
									{i < groupesHoraires.length - 1 ? <View style={{ width: 1, flex: 1, backgroundColor: colors.border }} /> : null}
								</View>

								<View style={{ flex: 1, paddingBottom: spacing.lg, gap: spacing.sm }}>
									<View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
										<Text variant="heading">{formatHeure(groupe.consumedAt)}</Text>
										<Text variant="caption" color="muted">
											{groupe.kcalTotal} kcal · {groupe.pctDER}% du DER
										</Text>
									</View>
									<Progress positionPct={Math.min(groupe.pctDER, 100)} color={tousValides ? colors.success : colors.primary} />

									{groupe.repasList.map((repas) => {
										const Icon = foodTypeIcon[repas.foodType];
										const isPending = patchMealEntry.isPending && patchMealEntry.variables?.id === repas.id;
										return (
											<View
												key={repas.id}
												style={{
													borderRadius: 12,
													borderWidth: 1,
													borderColor: repas.validated ? colors.success : colors.border,
													backgroundColor: repas.validated ? colors.successMuted : colors.muted,
													padding: spacing.md,
													gap: spacing.sm
												}}
											>
												<View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>
													<View
														style={{
															width: 36,
															height: 36,
															borderRadius: 10,
															alignItems: 'center',
															justifyContent: 'center',
															backgroundColor: repas.validated ? colors.success : colors.card
														}}
													>
														{repas.validated ? (
															<Check size={18} color={colors.background} />
														) : (
															<Icon size={18} color={colors.mutedForeground} />
														)}
													</View>
													<View style={{ flex: 1 }}>
														<View style={{ flexDirection: 'row', alignItems: 'baseline', gap: spacing.sm }}>
															<Text variant="bodyMedium" color="primary">
																{formatQuantite(repas)}
															</Text>
															<Text variant="caption" color="muted">
																{repas.kcal} kcal
															</Text>
														</View>
														<Text variant="caption" color="muted" numberOfLines={1}>
															{repas.food.name} ({repas.food.brand})
														</Text>
													</View>
													<Checkbox
														checked={repas.validated}
														disabled={isPending}
														onChange={(checked) => handleToggleValidated(repas, checked)}
													/>
												</View>

												<View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
													{repas.validated && repas.validatedBy && repas.validatedAt ? (
														<Text variant="caption" color="muted">
															coché par {repas.validatedBy.name} à {formatHeure(repas.validatedAt)}
														</Text>
													) : repas.validated ? (
														<Text variant="caption" color="muted">
															Distribué automatiquement — décochez si ce n'est pas le cas
														</Text>
													) : (
														<>
															<Text variant="caption" color="muted">
																{repas.locked ? 'Quantité fixée à la main' : "Quantité calculée par l'app"}
															</Text>
															<Button
																variant="ghost"
																label={ajustementOuvertId === repas.id ? 'Fermer' : 'Ajuster'}
																onPress={() => setAjustementOuvertId(ajustementOuvertId === repas.id ? null : repas.id)}
															/>
														</>
													)}
												</View>

												{ajustementOuvertId === repas.id && !repas.validated ? (
													<View style={{ gap: spacing.xs }}>
														<QuantitySlider
															value={repas.quantiteG}
															maximumValue={Math.max(repas.quantiteG * 2, 50)}
															step={sliderStep(repas)}
															formatValue={(v) => formatQuantitePreview(repas, v)}
															onCommit={(v) => handleSliderCommit(repas, v)}
														/>
														<Text variant="caption" color="muted">
															Ce créneau ne sera plus recalculé automatiquement tant que vous n'aurez pas
															réinitialisé la journée.
														</Text>
													</View>
												) : null}
											</View>
										);
									})}
								</View>
							</View>
						);
					})}
				</View>

				<Button
					variant="ghost"
					label="Repartir du calcul automatique"
					loading={resetRepartition.isPending}
					onPress={handleReset}
				/>
			</Card>
		</View>
	);
}

// app/src/lib/components/organisms/DailyMealSchedule.svelte
<script lang="ts">
	import Card from '$lib/components/atoms/Card.svelte';
	import Badge from '$lib/components/atoms/Badge.svelte';
	import Checkbox from '$lib/components/atoms/Checkbox.svelte';
	import Button from '$lib/components/atoms/Button.svelte';
	import Progress from '$lib/components/atoms/Progress.svelte';
	import Spinner from '$lib/components/atoms/Spinner.svelte';
	import Slider from '$lib/components/molecules/Slider.svelte';
	import Alert from '$lib/components/molecules/Alert.svelte';
	import RationScoreCard from '$lib/components/organisms/RationScoreCard.svelte';
	import RationSummaryCard from '$lib/components/organisms/RationSummaryCard.svelte';
	import type { NomNutrimentValide, StatutNutriment, SeuilNutriment } from '$lib/domain/nutrition.calc';
	import type { ScoreRation } from '$lib/domain/score.calc';
	import Beef from '@lucide/svelte/icons/beef';
	import Drumstick from '@lucide/svelte/icons/drumstick';
	import Fish from '@lucide/svelte/icons/fish';
	import RotateCcw from '@lucide/svelte/icons/rotate-ccw';
	import SlidersHorizontal from '@lucide/svelte/icons/sliders-horizontal';
	import Check from '@lucide/svelte/icons/check';

	type FoodType = 'croquette' | 'patee' | 'friandise';

	interface RationStatut {
		nutriment: NomNutrimentValide;
		valeur: number;
		statut: StatutNutriment;
		seuil: SeuilNutriment;
		positionPct: number;
	}

	type DistributionMode = 'gamelle' | 'distributeur_automatique' | 'gamelle_ludique';

	export interface RepasRepartition {
		id: string;
		consumedAt: string;
		foodType: FoodType;
		food: { id: string; name: string; brand: string; packageSizeG: number | null };
		quantiteG: number;
		kcal: number;
		locked: boolean;
		validated: boolean;
		validatedBy: { id: string; name: string } | null;
		validatedAt: string | null;
		distributionMode: DistributionMode;
	}

	export interface RepartitionOkResponse {
		success: true;
		rer: number;
		der: number;
		facteurDER: number;
		nombrePaquetsPatee: number | null;
		pateeNombrePaquetsOverride: number | null;
		repas: RepasRepartition[];
		ration: {
			totalKcal: number;
			statuts: RationStatut[];
			sousLeRER: boolean;
			glucidesParAliment: { foodId: string; foodName: string; pctMatiereSeche: number }[];
			fiabiliteParAliment: {
				foodId: string;
				foodName: string;
				emEstimee: boolean;
				humiditeEstimee: boolean;
				glucidesEstimes: boolean;
			}[];
			score: ScoreRation;
		};
		avertissements: string[];
	}

	let {
		repartition,
		catId,
		catName,
		date,
		onchange
	}: {
		repartition: RepartitionOkResponse;
		catId: string;
		catName: string;
		date: string;
		/** Appelé après tout PATCH/POST réussi (slider, coche, réinitialisation) pour recharger la répartition à jour. */
		onchange: () => void | Promise<void>;
	} = $props();

	let resetting = $state(false);
	let resetError = $state<string | null>(null);

	async function handleResetJournee() {
		if (
			!confirm(
				"Réinitialiser la journée ? Tous les repas déjà cochés « donné » ou ajustés seront effacés et recalculés depuis la routine."
			)
		) {
			return;
		}

		resetting = true;
		resetError = null;

		const response = await fetch('/api/repartition', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({ catId, date })
		});

		resetting = false;

		if (!response.ok) {
			resetError = 'Impossible de réinitialiser la journée.';
			return;
		}

		await onchange();
	}

	const foodTypeIcon: Record<FoodType, typeof Beef> = {
		croquette: Drumstick,
		patee: Beef,
		friandise: Fish
	};

	/** Libellé de la coche "donné" adapté au mode de distribution : le distributeur automatique donne
	 * sans intervention (coché d'office, on ne décoche que si ça n'a pas marché), la gamelle nécessite
	 * une action manuelle. */
	function labelDonne(repas: RepasRepartition): string {
		return repas.distributionMode === 'distributeur_automatique' ? 'Donné (auto)' : 'Donné à la main';
	}

	let sliderValues = $state<Record<string, number>>({});
	let pendingId = $state<string | null>(null);
	let actionError = $state<string | null>(null);
	/** Le slider d'un créneau reste caché derrière "Ajuster" : au quotidien on sert la quantité
	 * calculée et on coche, le réglage fin est l'exception. */
	let ajustementOuvert = $state<Record<string, boolean>>({});

	function sliderValue(repas: RepasRepartition): number {
		return sliderValues[repas.id] ?? repas.quantiteG;
	}

	/** Pas du slider : pour la pâtée, toujours un demi-paquet (jamais un quart ou un tiers de paquet,
	 * ça ne se mesure pas sur une balance de cuisine) — pour les autres types, le gramme. */
	function sliderStep(repas: RepasRepartition): number {
		return repas.foodType === 'patee' && repas.food.packageSizeG ? repas.food.packageSizeG / 2 : 0.5;
	}

	function formatQuantite(repas: RepasRepartition): string {
		if (repas.foodType === 'patee' && repas.food.packageSizeG) {
			const paquets = sliderValue(repas) / repas.food.packageSizeG;
			return `${paquets % 1 === 0 ? paquets : paquets.toFixed(1)} paquet${paquets > 1 ? 's' : ''}`;
		}
		return `${sliderValue(repas)} g`;
	}

	function formatHeure(consumedAt: string): string {
		return new Date(consumedAt).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
	}

	function formatHoraireCoche(validatedAt: string): string {
		return new Date(validatedAt).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
	}

	async function patchEntry(id: string, body: Record<string, unknown>): Promise<boolean> {
		pendingId = id;
		actionError = null;

		const response = await fetch(`/api/meal-entries/${id}`, {
			method: 'PATCH',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify(body)
		});

		pendingId = null;

		if (!response.ok) {
			actionError = "Impossible d'enregistrer ce changement.";
			return false;
		}

		return true;
	}

	function handleSliderInput(repas: RepasRepartition, value: number) {
		sliderValues[repas.id] = value;
	}

	async function handleSliderCommit(repas: RepasRepartition, value: number) {
		sliderValues[repas.id] = value;

		const ok = await patchEntry(repas.id, { quantityG: value });
		if (ok) await onchange();
	}

	async function handleToggleValidated(repas: RepasRepartition, nouvelleValeur: boolean) {
		const body: { validated: boolean; quantityG?: number } = { validated: nouvelleValeur };
		if (nouvelleValeur) body.quantityG = sliderValue(repas);

		const ok = await patchEntry(repas.id, body);
		if (ok) {
			delete sliderValues[repas.id];
			delete ajustementOuvert[repas.id];
			await onchange();
		}
	}

	const repasDonnes = $derived(repartition.repas.filter((r) => r.validated).length);
	const avancementPct = $derived(
		repartition.repas.length > 0 ? Math.round((repasDonnes / repartition.repas.length) * 100) : 0
	);
	/** Prochain repas non coché de la journée : c'est la seule ligne qui intéresse vraiment
	 * l'utilisateur quand il ouvre l'app en cuisine. */
	const prochainRepas = $derived(repartition.repas.find((r) => !r.validated) ?? null);

	interface GroupeHoraire {
		consumedAt: string;
		repasList: RepasRepartition[];
		kcalTotal: number;
		pctDER: number;
	}

	/** Regroupe les créneaux qui tombent exactement à la même heure (ex: pâtée + croquette à 8h) sous un
	 * même point de la timeline — on raisonne "à 8h, il se passe ça", pas une liste plate de lignes. */
	const groupesHoraires = $derived.by<GroupeHoraire[]>(() => {
		const parHeure = new Map<string, RepasRepartition[]>();
		for (const repas of repartition.repas) {
			const liste = parHeure.get(repas.consumedAt) ?? [];
			liste.push(repas);
			parHeure.set(repas.consumedAt, liste);
		}
		return [...parHeure.entries()]
			.sort(([a], [b]) => new Date(a).getTime() - new Date(b).getTime())
			.map(([consumedAt, repasList]) => {
				const kcalTotal = repasList.reduce((somme, r) => somme + r.kcal, 0);
				return {
					consumedAt,
					repasList,
					kcalTotal,
					pctDER: repartition.der > 0 ? Math.round((kcalTotal / repartition.der) * 100) : 0
				};
			});
	});
</script>

<RationScoreCard score={repartition.ration.score} {catName} />

{#each repartition.avertissements as avertissement}
	<Alert variant="warning">{avertissement}</Alert>
{/each}

<RationSummaryCard {repartition} />

<Card>
	{#snippet header()}
		<div class="flex flex-col gap-0.5">
			<h3 class="text-[17px] leading-tight">Repas du jour</h3>
			<p class="text-xs text-muted-foreground">
				{#if repartition.repas.length === 0}
					Aucun créneau prévu aujourd'hui.
				{:else if repasDonnes === repartition.repas.length}
					Tous les repas ont été donnés. 🎉
				{:else if prochainRepas}
					Prochain : {formatHeure(prochainRepas.consumedAt)} — {formatQuantite(prochainRepas)} de {prochainRepas.food.name}
				{/if}
			</p>
		</div>
		<Badge variant={repasDonnes === repartition.repas.length ? 'success' : 'default'}>
			{repasDonnes} / {repartition.repas.length} donnés
		</Badge>
	{/snippet}

	<Progress value={avancementPct} tone={repasDonnes === repartition.repas.length ? 'success' : 'primary'} />

	{#if resetError}<Alert variant="danger">{resetError}</Alert>{/if}

	<div class="flex flex-col">
		{#each groupesHoraires as groupe, i (groupe.consumedAt)}
			{@const tousValides = groupe.repasList.every((r) => r.validated)}
			<div class="relative flex gap-3">
				<div class="flex flex-col items-center">
					<span
						class="mt-1.5 flex size-3 shrink-0 rounded-full {tousValides
							? 'bg-success'
							: 'bg-primary'}"
					></span>
					{#if i < groupesHoraires.length - 1}
						<span class="w-px flex-1 bg-border"></span>
					{/if}
				</div>

				<div class="flex-1 pb-5">
					<div class="mb-1.5 flex items-center justify-between gap-2">
						<span class="font-heading text-sm font-semibold text-foreground">
							{formatHeure(groupe.consumedAt)}
						</span>
						<span class="text-xs text-muted-foreground">{groupe.kcalTotal} kcal · {groupe.pctDER}% du DER</span>
					</div>
					<div class="mb-2.5 h-1.5 w-full overflow-hidden rounded-full bg-muted">
						<div
							class="h-full rounded-full {tousValides ? 'bg-success' : 'bg-primary'}"
							style="width: {Math.min(groupe.pctDER, 100)}%"
						></div>
					</div>

					<div class="flex flex-col gap-2">
						{#each groupe.repasList as repas (repas.id)}
							{@const Icon = foodTypeIcon[repas.foodType]}
							<div
								class="flex flex-col gap-2 rounded-lg border px-3.5 py-3 transition-colors {repas.validated
									? 'border-success/30 bg-success-muted/40'
									: 'border-border bg-muted/30'}"
							>
								<div class="flex items-center gap-3">
									<span
										class="flex size-9 shrink-0 items-center justify-center rounded-lg {repas.validated
											? 'bg-success text-background'
											: 'bg-muted text-muted-foreground'}"
									>
										{#if repas.validated}<Check class="size-4.5" />{:else}<Icon class="size-4.5" />{/if}
									</span>

									<div class="flex min-w-0 flex-1 flex-col">
										<span class="flex items-baseline gap-2">
											<span class="font-heading text-sm font-bold text-primary">{formatQuantite(repas)}</span>
											<span class="text-xs text-muted-foreground">{repas.kcal} kcal</span>
										</span>
										<span class="truncate text-xs text-muted-foreground">{repas.food.name} ({repas.food.brand})</span>
									</div>

									<Checkbox
										checked={repas.validated}
										disabled={pendingId === repas.id}
										onchange={(e) => handleToggleValidated(repas, (e.target as HTMLInputElement).checked)}
									>
										{pendingId === repas.id ? '…' : labelDonne(repas)}
									</Checkbox>
								</div>

								<div class="flex items-center justify-between gap-2">
									{#if repas.validated && repas.validatedBy && repas.validatedAt}
										<span class="text-xs text-muted-foreground">
											coché par {repas.validatedBy.name} à {formatHoraireCoche(repas.validatedAt)}
										</span>
									{:else if repas.validated}
										<span class="text-xs text-muted-foreground">Distribué automatiquement — décochez si ce n'est pas le cas</span>
									{:else}
										<span class="text-xs text-muted-foreground">
											{repas.locked ? 'Quantité fixée à la main' : "Quantité calculée par l'app"}
										</span>
										<Button
											variant="ghost"
											size="sm"
											onclick={() => (ajustementOuvert[repas.id] = !ajustementOuvert[repas.id])}
										>
											<SlidersHorizontal />
											{ajustementOuvert[repas.id] ? 'Fermer' : 'Ajuster'}
										</Button>
									{/if}
								</div>

								{#if ajustementOuvert[repas.id] && !repas.validated}
									<Slider
										valueLabel={formatQuantite(repas)}
										min={0}
										max={Math.max(repas.quantiteG * 2, 50)}
										step={sliderStep(repas)}
										value={sliderValue(repas)}
										oninput={(v) => handleSliderInput(repas, v)}
										onchange={(v) => handleSliderCommit(repas, v)}
									/>
									<p class="text-xs text-muted-foreground">
										Ce créneau ne sera plus recalculé automatiquement tant que vous n'aurez pas réinitialisé la
										journée.
									</p>
								{/if}
							</div>
						{/each}
					</div>
				</div>
			</div>
		{/each}
	</div>

	{#if actionError}<Alert variant="danger">{actionError}</Alert>{/if}

	<Button variant="ghost" size="sm" class="w-fit" onclick={handleResetJournee} disabled={resetting}>
		{#if resetting}<Spinner />{:else}<RotateCcw />{/if}
		Repartir du calcul automatique
	</Button>
</Card>
