// mobile/src/design-system/organisms/HouseholdMembersPanel.tsx
import { useState } from 'react';
import { View, Alert as RNAlert } from 'react-native';
import { Trash2 } from 'lucide-react-native';
import type { CatMember } from '@shared/cat';
import { Text } from '../atoms/Text';
import { Input } from '../atoms/Input';
import { Button } from '../atoms/Button';
import { Spinner } from '../atoms/Spinner';
import { IconButton } from '../atoms/IconButton';
import { FormField } from '../molecules/FormField';
import { Alert } from '../molecules/Alert';
import { colors, spacing } from '../tokens';
import { useAddCatMember, useCatMembers, useRemoveCatMember } from '../../api/catMembers';
import { useCurrentUser } from '../../api/auth';
import { ApiError } from '../../api/client';

interface HouseholdMembersPanelProps {
	catId: string;
}

export function HouseholdMembersPanel({ catId }: HouseholdMembersPanelProps) {
	const { data: members, isLoading, isError } = useCatMembers(catId);
	const { data: session } = useCurrentUser();
	const currentUserId = session?.user.id;
	const addMember = useAddCatMember(catId);
	const removeMember = useRemoveCatMember(catId);
	const [email, setEmail] = useState('');
	const [inviteError, setInviteError] = useState<string | null>(null);

	async function handleInvite() {
		setInviteError(null);
		if (!email.trim()) {
			setInviteError('Adresse email requise.');
			return;
		}
		try {
			await addMember.mutateAsync(email);
			setEmail('');
		} catch (err) {
			setInviteError(err instanceof ApiError ? err.message : "Impossible d'ajouter cette personne.");
		}
	}

	function handleRemove(member: CatMember) {
		RNAlert.alert(
			member.userId === currentUserId ? 'Quitter le foyer ?' : `Retirer ${member.name} ?`,
			member.userId === currentUserId
				? 'Vous ne verrez plus le suivi de ce chat.'
				: `Retirer ${member.name} du foyer de ce chat ?`,
			[
				{ text: 'Annuler', style: 'cancel' },
				{ text: 'Retirer', style: 'destructive', onPress: () => removeMember.mutate(member.membershipId) }
			]
		);
	}

	return (
		<View style={{ gap: spacing.lg }}>
			<Text variant="caption" color="muted">
				Toute personne du foyer voit le même suivi pour ce chat (repas, routine, poids) — pas besoin de ressaisir
				quoi que ce soit chacun de son côté.
			</Text>

			<View style={{ flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-end' }}>
				<View style={{ flex: 1 }}>
					<FormField label="Email d'un compte existant">
						<Input value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="prenom@exemple.fr" />
					</FormField>
				</View>
				<Button label="Ajouter" onPress={handleInvite} loading={addMember.isPending} />
			</View>
			{inviteError ? <Alert variant="error" message={inviteError} /> : null}

			{isLoading ? (
				<Spinner />
			) : isError ? (
				<Alert variant="error" message="Impossible de charger le foyer." />
			) : (
				<View style={{ gap: spacing.xs }}>
					{members?.map((member) => (
						<View
							key={member.membershipId}
							style={{
								flexDirection: 'row',
								alignItems: 'center',
								justifyContent: 'space-between',
								borderRadius: 10,
								borderWidth: 1,
								borderColor: colors.border,
								backgroundColor: colors.muted,
								paddingVertical: spacing.sm,
								paddingHorizontal: spacing.md
							}}
						>
							<View>
								<Text variant="bodyMedium">
									{member.name}
									{member.userId === currentUserId ? ' (vous)' : ''}
								</Text>
								<Text variant="caption" color="muted">
									{member.email}
								</Text>
							</View>
							<IconButton onPress={() => handleRemove(member)}>
								{removeMember.isPending && removeMember.variables === member.membershipId ? (
									<Spinner />
								) : (
									<Trash2 size={18} color={colors.destructive} />
								)}
							</IconButton>
						</View>
					))}
				</View>
			)}
		</View>
	);
}

// app/src/lib/components/organisms/HouseholdMembersPanel.svelte
<script lang="ts">
	import Button from '$lib/components/atoms/Button.svelte';
	import Input from '$lib/components/atoms/Input.svelte';
	import IconButton from '$lib/components/atoms/IconButton.svelte';
	import Spinner from '$lib/components/atoms/Spinner.svelte';
	import FormField from '$lib/components/molecules/FormField.svelte';
	import Alert from '$lib/components/molecules/Alert.svelte';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import UserPlus from '@lucide/svelte/icons/user-plus';

	interface Member {
		membershipId: string;
		userId: string;
		name: string;
		email: string;
	}

	let { catId, currentUserId }: { catId: string; currentUserId: string } = $props();

	let members = $state<Member[]>([]);
	let loading = $state(true);
	let loadError = $state<string | null>(null);

	let email = $state('');
	let inviting = $state(false);
	let inviteError = $state<string | null>(null);

	let removingId = $state<string | null>(null);
	let removeError = $state<string | null>(null);

	async function load() {
		loading = true;
		loadError = null;
		const response = await fetch(`/api/v1/cats/${catId}/members`);
		if (response.ok) {
			const body = await response.json();
			members = body.members;
		} else {
			loadError = 'Impossible de charger le foyer.';
		}
		loading = false;
	}

	$effect(() => {
		load();
	});

	async function handleInvite(event: SubmitEvent) {
		event.preventDefault();
		inviteError = null;

		if (!email.trim()) {
			inviteError = 'Adresse email requise.';
			return;
		}

		inviting = true;
		const response = await fetch(`/api/v1/cats/${catId}/members`, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({ email })
		});
		inviting = false;

		if (!response.ok) {
			const body = await response.json().catch(() => ({}));
			inviteError = body.error ?? "Impossible d'ajouter cette personne.";
			return;
		}

		email = '';
		await load();
	}

	async function handleRemove(member: Member) {
		if (
			!confirm(
				member.userId === currentUserId
					? 'Quitter le foyer de ce chat ? Vous ne verrez plus son suivi.'
					: `Retirer ${member.name} du foyer de ce chat ?`
			)
		) {
			return;
		}

		removingId = member.membershipId;
		removeError = null;

		const response = await fetch(`/api/v1/cats/${catId}/members/${member.membershipId}`, { method: 'DELETE' });
		removingId = null;

		if (!response.ok) {
			const body = await response.json().catch(() => ({}));
			removeError = body.error ?? 'Impossible de retirer ce membre.';
			return;
		}

		await load();
	}
</script>

<div class="flex flex-col gap-4">
	<p class="text-sm text-muted-foreground">
		Toute personne du foyer voit le même suivi pour ce chat (repas, routine, poids) — pas besoin de
		ressaisir quoi que ce soit chacun de son côté.
	</p>

	<form class="flex items-end gap-2" onsubmit={handleInvite}>
		<div class="flex-1">
			<FormField label="Email d'un compte existant" for="member-email">
				<Input id="member-email" type="email" placeholder="prenom@exemple.fr" bind:value={email} autocomplete="off" />
			</FormField>
		</div>
		<Button type="submit" disabled={inviting}>
			{#if inviting}<Spinner />{:else}<UserPlus />{/if}
			Ajouter
		</Button>
	</form>
	{#if inviteError}<Alert variant="danger">{inviteError}</Alert>{/if}

	{#if loading}
		<Spinner />
	{:else if loadError}
		<Alert variant="danger">{loadError}</Alert>
	{:else}
		<div class="flex flex-col gap-1.5">
			{#each members as member (member.membershipId)}
				<div class="flex items-center justify-between gap-2 rounded-lg border border-border bg-muted/30 px-3 py-2">
					<div class="flex flex-col">
						<span class="text-sm font-medium text-foreground">
							{member.name}{member.userId === currentUserId ? ' (vous)' : ''}
						</span>
						<span class="text-xs text-muted-foreground">{member.email}</span>
					</div>
					<IconButton
						label={member.userId === currentUserId ? 'Quitter le foyer' : 'Retirer du foyer'}
						variant="danger"
						onclick={() => (removingId === member.membershipId ? undefined : handleRemove(member))}
					>
						{#if removingId === member.membershipId}<Spinner />{:else}<Trash2 />{/if}
					</IconButton>
				</div>
			{/each}
		</div>
		{#if removeError}<Alert variant="danger">{removeError}</Alert>{/if}
	{/if}
</div>
