// mobile/src/design-system/organisms/RationSummaryCard.tsx
import { View } from 'react-native';
import { Flame, Drumstick, Beef, Fish, Container, Hand } from 'lucide-react-native';
import type { RepartitionOkResponse } from '@shared/repartition';
import { Card } from '../atoms/Card';
import { Text } from '../atoms/Text';
import { Progress } from '../atoms/Progress';
import { colors, radii, spacing } from '../tokens';

interface RationSummaryCardProps {
	repartition: RepartitionOkResponse;
}

const foodTypeIcon = { croquette: Drumstick, patee: Beef, friandise: Fish } as const;

export function RationSummaryCard({ repartition }: RationSummaryCardProps) {
	const progressionPct = repartition.der > 0 ? Math.min(100, Math.round((repartition.ration.totalKcal / repartition.der) * 100)) : 0;

	const foodIdsEmEstimee = new Set(repartition.ration.fiabiliteParAliment.filter((a) => a.emEstimee).map((a) => a.foodId));
	const typeReposeSurEmEstimee = (type: keyof typeof foodTypeIcon) =>
		repartition.repas.some((r) => r.foodType === type && foodIdsEmEstimee.has(r.food.id));

	const totaux = repartition.totauxParType;

	return (
		<Card style={{ gap: spacing.md }}>
			<View style={{ gap: spacing.sm }}>
				<View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>
					<View
						style={{
							width: 40,
							height: 40,
							borderRadius: radii.md,
							backgroundColor: colors.primaryMuted,
							alignItems: 'center',
							justifyContent: 'center'
						}}
					>
						<Flame size={20} color={colors.primary} />
					</View>
					<View style={{ flex: 1 }}>
						<Text>
							<Text variant="heading" style={{ fontSize: 20 }}>
								{Math.round(repartition.ration.totalKcal)}
							</Text>
							<Text color="muted"> / {Math.round(repartition.der)} kcal</Text>
						</Text>
						<Text variant="caption" color="muted">
							({progressionPct}%) — RER {Math.round(repartition.rer)} kcal, facteur {repartition.facteurDER}
						</Text>
					</View>
				</View>
				<Progress positionPct={progressionPct} />
			</View>

			<View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, alignItems: 'center' }}>
				<Text variant="caption" style={{ textTransform: 'uppercase' }}>
					Total du jour
				</Text>
				{(['croquette', 'patee', 'friandise'] as const).map((type) => {
					if (totaux[type] <= 0) return null;
					const Icon = foodTypeIcon[type];
					return (
						<View key={type} style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}>
							<Icon size={16} color={colors.mutedForeground} />
							<Text variant="caption" color="muted">
								{Math.round(totaux[type])} g{typeReposeSurEmEstimee(type) ? '*' : ''}
							</Text>
						</View>
					);
				})}
			</View>

			{repartition.recapCroquette && repartition.recapCroquette.distributeurAutomatiqueG > 0 ? (
				<View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, alignItems: 'center' }}>
					<Text variant="caption" style={{ textTransform: 'uppercase' }}>
						Croquette — qui distribue quoi
					</Text>
					<View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}>
						<Container size={16} color={colors.mutedForeground} />
						<Text variant="caption" color="muted">
							{Math.round(repartition.recapCroquette.distributeurAutomatiqueG)} g déjà dans le distributeur
						</Text>
					</View>
					{repartition.recapCroquette.aPreparerG > 0 ? (
						<View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}>
							<Hand size={16} color={colors.mutedForeground} />
							<Text variant="caption" color="muted">
								{Math.round(repartition.recapCroquette.aPreparerG)} g à préparer vous-même
							</Text>
						</View>
					) : null}
				</View>
			) : null}
		</Card>
	);
}

// app/src/lib/components/organisms/RationSummaryCard.svelte
<script lang="ts">
	import Card from '$lib/components/atoms/Card.svelte';
	import Progress from '$lib/components/atoms/Progress.svelte';
	import Beef from '@lucide/svelte/icons/beef';
	import Drumstick from '@lucide/svelte/icons/drumstick';
	import Fish from '@lucide/svelte/icons/fish';
	import Flame from '@lucide/svelte/icons/flame';
	import Container from '@lucide/svelte/icons/container';
	import Hand from '@lucide/svelte/icons/hand';
	import type { RepartitionOkResponse } from './DailyMealSchedule.svelte';

	type FoodType = 'croquette' | 'patee' | 'friandise';

	let { repartition }: { repartition: RepartitionOkResponse } = $props();

	const totauxParType = $derived(repartition.totauxParType);

	const foodIdsEmEstimee = $derived(
		new Set(repartition.ration.fiabiliteParAliment.filter((a) => a.emEstimee).map((a) => a.foodId))
	);

	function typeReposeSurEmEstimee(type: FoodType): boolean {
		return repartition.repas.some((r) => r.foodType === type && foodIdsEmEstimee.has(r.food.id));
	}

	const progressionPct = $derived(
		repartition.der > 0 ? Math.min(100, Math.round((repartition.ration.totalKcal / repartition.der) * 100)) : 0
	);
</script>

<Card>
	<div class="flex flex-col gap-2">
		<div class="flex items-center gap-2.5">
			<span class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary-muted text-primary">
				<Flame class="size-5" />
			</span>
			<p class="text-foreground">
				<strong class="font-heading text-2xl">{Math.round(repartition.ration.totalKcal)}</strong>
				<span class="text-lg text-muted-foreground">/ {Math.round(repartition.der)} kcal</span>
				<span class="block text-xs text-muted-foreground sm:inline">
					({progressionPct}%) — RER {Math.round(repartition.rer)} kcal, facteur {repartition.facteurDER}
				</span>
			</p>
		</div>
		<Progress value={progressionPct} />
	</div>

	<p class="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
		<span class="font-heading text-xs font-semibold tracking-wide text-foreground uppercase">Total du jour</span>
		{#if totauxParType.croquette > 0}
			<span class="inline-flex items-center gap-1.5">
				<Drumstick class="size-4" />
				{Math.round(totauxParType.croquette)} g{typeReposeSurEmEstimee('croquette') ? '*' : ''}
			</span>
		{/if}
		{#if totauxParType.patee > 0}
			<span class="inline-flex items-center gap-1.5">
				<Beef class="size-4" />
				{Math.round(totauxParType.patee)} g{typeReposeSurEmEstimee('patee') ? '*' : ''}
			</span>
		{/if}
		{#if totauxParType.friandise > 0}
			<span class="inline-flex items-center gap-1.5">
				<Fish class="size-4" />
				{Math.round(totauxParType.friandise)} g{typeReposeSurEmEstimee('friandise') ? '*' : ''}
			</span>
		{/if}
	</p>

	{#if repartition.recapCroquette && repartition.recapCroquette.distributeurAutomatiqueG > 0}
		<p class="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
			<span class="font-heading text-xs font-semibold tracking-wide text-foreground uppercase">
				Croquette — qui distribue quoi
			</span>
			<span class="inline-flex items-center gap-1.5">
				<Container class="size-4" />
				{Math.round(repartition.recapCroquette.distributeurAutomatiqueG)} g déjà dans le distributeur
			</span>
			{#if repartition.recapCroquette.aPreparerG > 0}
				<span class="inline-flex items-center gap-1.5">
					<Hand class="size-4" />
					{Math.round(repartition.recapCroquette.aPreparerG)} g à préparer vous-même
				</span>
			{/if}
		</p>
	{/if}
</Card>
